USE MusicDatabase;
GO

CREATE INDEX IX_PAYMENT_CREDITNUMBER ON Payment(CreditNumber);

CREATE INDEX IX_MUSICORDER_ORDERDATE ON MusicOrder(OrderDate);

CREATE INDEX IX_CUSTOMER_CUSTOMERNAME ON Customer(CustomerName);

CREATE INDEX IX_SHIPPING_SHIPPINGDAY ON Shipping(ShippingDay);

CREATE INDEX IX_ALBUMGENRES_GENRES ON AlbumGenres(Genre);

CREATE INDEX IX_ARTISTNAMES_ARTISTS ON Artists(ArtistName);

CREATE INDEX IX_MUSICCOMPANYNAME_MUSICCOMPANY ON MusicCompany(MusicCompanyName);

CREATE INDEX IX_SONGNAME_SONGS ON Songs(SongName);

CREATE INDEX IX_ALBUMS_ALBUMNAME ON Albums(AlbumName);

CREATE INDEX IX_CUSTOMERNUMBER_PHONENUMBER ON CustomerNumber(PhoneNumber);


GO
